# Generated by Django 5.1.4 on 2024-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Hero section title", max_length=200),
                ),
                ("subtitle", models.TextField(help_text="Hero section subtitle")),
                ("description", models.TextField(help_text="Hero section description")),
                (
                    "image",
                    models.ImageField(
                        help_text="Hero section image", upload_to="hero_images/"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Shop Now", help_text="Button text", max_length=50
                    ),
                ),
                ("button_url", models.URLField(default="#", help_text="Button link")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "secondary_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service or product", max_length=100
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product/service",
                        max_digits=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image for the service or product",
                        upload_to="service_images/",
                    ),
                ),
            ],
        ),
    ]
