# Generated by Django 5.1.4 on 2024-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="image",
            field=models.ImageField(help_text="Hero section image", upload_to=""),
        ),
    ]
