# Generated by Django 5.1.4 on 2024-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_aboutsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Main heading for the benefits section",
                        max_length=200,
                    ),
                ),
                (
                    "subheading",
                    models.CharField(
                        help_text="Subheading for the section", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Brief description of the benefits"),
                ),
                (
                    "benefit_1",
                    models.CharField(help_text="First benefit", max_length=200),
                ),
                (
                    "benefit_2",
                    models.CharField(help_text="Second benefit", max_length=200),
                ),
                (
                    "benefit_3",
                    models.CharField(help_text="Third benefit", max_length=200),
                ),
                (
                    "benefit_4",
                    models.CharField(help_text="Fourth benefit", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image for the benefits section",
                        upload_to="benefits_images/",
                    ),
                ),
            ],
        ),
    ]
