# Generated by Django 4.2.11 on 2025-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0006_contactimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(help_text="FAQ question", max_length=255),
                ),
                ("answer", models.TextField(help_text="FAQ answer")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the FAQ"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image for the FAQ",
                        null=True,
                        upload_to="faq_images/",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
