# Generated by Django 4.2.11 on 2025-01-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0007_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title for the FAQ section", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Short description for the FAQ section"),
                ),
                (
                    "side_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image to display in the FAQ section",
                        null=True,
                        upload_to="faq_images/",
                    ),
                ),
            ],
        ),
    ]
