# Generated by Django 4.2.11 on 2025-01-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0008_faqsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the service", null=True
            ),
        ),
    ]
