# Generated by Django 4.2.11 on 2025-01-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0009_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
