# Generated by Django 4.2.11 on 2025-01-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0010_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="strength",
            field=models.IntegerField(
                choices=[(25, "25%"), (50, "50%"), (75, "75%"), (100, "100%")],
                default=50,
                help_text="Strength level of the product",
            ),
        ),
    ]
