# Generated by Django 4.2.11 on 2025-01-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0011_service_strength"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Strong Poppers', 'Beginner Friendly')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Uncheck to hide the product from listings."
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a category for the product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myApp.category",
            ),
        ),
    ]
